### ISSUE TITLE
about the training

### ISSUE THREAD

**Issue by lofangmeng** [ShihaoZhaoZSH/Uni-ControlNet#26]
I hope this message finds you well.

I have a couple of questions regarding model training and input methods that I would greatly appreciate your insights on:

If I have three types of conditions, such as color condition, segmentation condition, and depth condition, is it feasible to train a model using these multiple conditions simultaneously?
Is it possible to use embeddings as input for prompts instead of traditional text captions? If so, could you provide some guidance or resources on how to implement this?
Thank you very much for your time and assistance.

**Comment by chaunceywx** [comment]
Hello, I also want to train uni-control on other dataset. Do you meet the the following error when build init_local.ckpt?
python utils/prepare_weights.py init_local ./ckpt/v1-5-pruned.ckpt configs/local_v15.yaml ckpt/init_local.ckpt
```
Traceback (most recent call last):
  File "E:\code\Uni-ControlNet-main\utils\prepare_weights.py", line 77, in <module>
    init_local(sys.argv[2], sys.argv[3], sys.argv[4])
  File "E:\code\Uni-ControlNet-main\utils\prepare_weights.py", line 24, in init_local
    model.load_state_dict(target_dict, strict=True)
  File "F:\conda_env\envs\HumanSD_21\lib\site-packages\torch\nn\modules\module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for UniControlNet:
        size mismatch for cond_stage_model.transformer.text_model.embeddings.token_embedding.weight: copying a param with shape torch.Size([49408, 768]) from checkpoint, the shape in current model is torch.Size([49408, 512]).
        size mismatch for cond_stage_model.transformer.text_model.embeddings.position_embedding.weight: copying a param with shape torch.Size([77, 768]) from checkpoint, the shape in current model is torch.Size([77, 512]).
        size mismatch for cond_stage_model.transformer.text_model.encoder.layers.0.self_attn.k_proj.weight: copying a param with shape torch.Size([768, 768]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for cond_stage_model.transformer.text_model.encoder.layers.0.self_attn.k_proj.bias: copying a param with shape torch.Size([768]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for cond_stage_model.transformer.text_model.encoder.layers.0.self_attn.v_proj.weight: copying a param with shape torch.Size([768, 768]) from checkpoint, the shape in current model is torch.Size([512, 512]).
```
