### ISSUE TITLE
About local and global integrate

### ISSUE THREAD

**Issue by liangbingzhao** [ShihaoZhaoZSH/Uni-ControlNet#27]
Thanks for your great job. I tried to train uni-controlnet on celebahq. Seperately, the local adapter and global adapter's results seem good, like following
local adapter:
![image](https://github.com/user-attachments/assets/7691bb76-ea08-419a-a6e1-ff3a77c29650)
global adapter:
![image](https://github.com/user-attachments/assets/d6cf6161-8971-4ee6-97f6-6819da022ad8)
But after integrate, the model generate such things:
![image](https://github.com/user-attachments/assets/82dabb9b-47f8-4a54-ab69-fe19dc3cd104)
![image](https://github.com/user-attachments/assets/9d265c50-35cb-436b-b245-daa3630abb6b)

Is there anything need to notice when doing the local global integration?

**Comment by chaunceywx** [comment]
Hello, I also want to train  uni-control on other dataset. Do you meet the the following error when build init_local.ckpt?
python utils/prepare_weights.py init_local ./ckpt/v1-5-pruned.ckpt configs/local_v15.yaml ckpt/init_local.ckpt

```
Traceback (most recent call last):
  File "E:\code\Uni-ControlNet-main\utils\prepare_weights.py", line 77, in <module>
    init_local(sys.argv[2], sys.argv[3], sys.argv[4])
  File "E:\code\Uni-ControlNet-main\utils\prepare_weights.py", line 24, in init_local
    model.load_state_dict(target_dict, strict=True)
  File "F:\conda_env\envs\HumanSD_21\lib\site-packages\torch\nn\modules\module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for UniControlNet:
        size mismatch for cond_stage_model.transformer.text_model.embeddings.token_embedding.weight: copying a param with shape torch.Size([49408, 768]) from checkpoint, the shape in current model is torch.Size([49408, 512]).
        size mismatch for cond_stage_model.transformer.text_model.embeddings.position_embedding.weight: copying a param with shape torch.Size([77, 768]) from checkpoint, the shape in current model is torch.Size([77, 512]).
        size mismatch for cond_stage_model.transformer.text_model.encoder.layers.0.self_attn.k_proj.weight: copying a param with shape torch.Size([768, 768]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for cond_stage_model.transformer.text_model.encoder.layers.0.self_attn.k_proj.bias: copying a param with shape torch.Size([768]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for cond_stage_model.transformer.text_model.encoder.layers.0.self_attn.v_proj.weight: copying a param with shape torch.Size([768, 768]) from checkpoint, the shape in current model is torch.Size([512, 512]).
```
